services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: react-flask-app-api
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-flask-app-client
    ports:
      - "3000:80"